CREATE TABLE passwords (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_email VARCHAR(60) NOT NULL FOREIGN KEY REFERENCES users(email) ON DELETE CASCADE,
    site_url VARCHAR(255) NOT NULL UNIQUE,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);